apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: btc-light-client-btc-types
  title: BTC Light Client btc-types
  tags:
    - near
  links: []
  annotations:
    aurora.dev/security-tier: "1"
spec:
  owner: nearone-team
  type: library
  lifecycle: production
