apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: btc-light-client-relayer
  title: BTC Light Client relayer
  tags:
    - near
  links: []
  annotations:
    aurora.dev/security-tier: "1"
spec:
  owner: nearone-team
  type: service
  lifecycle: production
  deployedAt: []
  interactsWith: []
