name: Rust

on:
  push:
    branches: ["main"]
  pull_request:

env:
  CARGO_TERM_COLOR: always

permissions:
  checks: write

jobs:
  contract:
    name: "Smart contract checks"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./contract
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install cargo-near
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/near/cargo-near/releases/latest/download/cargo-near-installer.sh | sh

      - name: Run rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path ./contract/Cargo.toml --all -- --check

      - name: Run clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --manifest-path ./contract/Cargo.toml --all-targets -- -D warnings -D clippy::pedantic -D clippy::as_conversions -A clippy::must_use_candidate

      - name: Run tests
        run: |
          rustup target add wasm32-unknown-unknown
          RUST_BACKTRACE=1 cargo test -- --skip test_setting_genesis_block --skip test_setting_chain_reorg

      - name: Run tests zcash
        run: |
          rustup target add wasm32-unknown-unknown
          RUST_BACKTRACE=1 cargo test --features zcash --no-default-features

  relayer:
    name: "Relayer checks"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./relayer
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Run rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path ./relayer/Cargo.toml --all -- --check

      - name: Run clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --manifest-path ./relayer/Cargo.toml --all-targets -- -D warnings -D clippy::pedantic -D clippy::as_conversions

      - name: Run tests
        run: |
          RUST_BACKTRACE=1 cargo test
