on:
  push:
    tags:
      - 'btc-light-client-v[0-9]+.[0-9]+.[0-9]+*'

  workflow_dispatch:

name: Update Contracts
jobs:
  update-contracts:
    runs-on: ubuntu-latest
    name: Update Contracts
    permissions:
      contents: write
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
      - name: Install cargo-near
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/near/cargo-near/releases/latest/download/cargo-near-installer.sh | sh
      - name: Build contract
        run: |
          cd contract
          
          cargo near build reproducible-wasm
          mv ./target/near/btc_light_client_contract.wasm ./target/near/btc_light_client_contract_bitcoin.wasm
          
          cargo near build reproducible-wasm --variant bitcoin_testnet
          mv ./target/near/btc_light_client_contract.wasm ./target/near/btc_light_client_contract_bitcoin_testnet.wasm
          
          cargo near build reproducible-wasm --variant litecoin
          mv ./target/near/btc_light_client_contract.wasm ./target/near/btc_light_client_contract_litecoin.wasm
          
          cargo near build reproducible-wasm --variant litecoin_testnet
          mv ./target/near/btc_light_client_contract.wasm ./target/near/btc_light_client_contract_litecoin_testnet.wasm
          
          cargo near build reproducible-wasm --variant zcash
          mv ./target/near/btc_light_client_contract.wasm ./target/near/btc_light_client_contract_zcash.wasm
        timeout-minutes: 60
      - name: Archive built WASM files
        env:
           RAW_TAG: ${{ github.ref_name }}
        run: |
          SAFE_TAG="${RAW_TAG//./-}"
          ZIP_NAME="${SAFE_TAG}.zip"
          mkdir -p artifacts
          find ./contract/target/near -name "*.wasm" -exec cp {} artifacts/ \;
          zip -j "$ZIP_NAME" artifacts/*
        shell: bash
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: "*.zip"
